name: CookieMinion
description: A ultra-lightweight version of CookieMonster
main: me.jascotty2.cookieminion.CookieMinion
version: 1.13.3
api-version: 1.13
author: jascotty2
loadbefore: [WorldGuard]
softdepend: [Vault, CookieMonster]
website: "https://dev.bukkit.org/projects/cookieminion"
commands:
  cookieminion:
    description: Admin Commands
    usage: /cookieminion reload
    aliases: [cm]
    permission: cookiemonster.admin
permissions:
  cookiemonster.admin:
    default: op